@startyaml args
O:
    struct QEMUOption:
        - const char *name;
        - int flags;
        - int index;
        - uint32_t arch_mask;
    
    QEMUOption qemu_options[
        sdf
    ];

@end